### ISSUE TITLE
Cache wiki page contents in Redis

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor_core#9]
Right now, the bot requests each wiki stub as it's needed. This is very inefficient.

**Tasks:**
- [ ] No stubs are downloaded on initialization
- [ ] When a stub is requested, it's downloaded and stored in Redis
- [ ] On a reload, the caches are cleared

**Comment by itsthejoker** [comment]
This issue is invalidated by the move to local json configs; do we still want to keep it open?

**Comment by TheLonelyGhost** [comment]
Nah, we should be good to "never" this one.
